// GET /api/overview/progress
// Token-gated read of the Overview compilation progress (data/tafsir_overview/_progress.json).
// Auth mirrors functions/api/feedback/admin.js: a shared token in env.OVERVIEW_ADMIN_TOKEN,
// passed as `Authorization: Bearer <token>` or `X-Overview-Admin-Token`.
//
// The progress file is regenerated by scripts/overview_progress.py and deployed with the
// site, so the console reflects the last deploy (add a KV push later if you want live counts).

function jsonResponse(payload, status = 200) {
    return new Response(JSON.stringify(payload), {
        status,
        headers: { "Content-Type": "application/json", "Cache-Control": "no-store" },
    });
}

function requireAdmin(request, env) {
    const configured = env.OVERVIEW_ADMIN_TOKEN;
    if (!configured) {
        return { ok: false, response: jsonResponse({ ok: false, error: "Overview console token is not configured." }, 503) };
    }
    const header = request.headers.get("Authorization") || "";
    const bearer = header.startsWith("Bearer ") ? header.slice("Bearer ".length).trim() : "";
    const alt = request.headers.get("X-Overview-Admin-Token") || "";
    if (bearer === configured || alt === configured) return { ok: true };
    return { ok: false, response: jsonResponse({ ok: false, error: "Unauthorized" }, 401) };
}

export async function onRequestGet(context) {
    const { request, env } = context;
    const auth = requireAdmin(request, env);
    if (!auth.ok) return auth.response;

    try {
        const url = new URL("/data/tafsir_overview/_progress.json", request.url);
        const res = await env.ASSETS.fetch(new Request(url.toString()));
        if (!res.ok) {
            return jsonResponse({ ok: false, error: "No progress data deployed yet." }, 404);
        }
        const progress = await res.json();
        return jsonResponse({ ok: true, progress });
    } catch (e) {
        return jsonResponse({ ok: false, error: String(e && e.message ? e.message : e) }, 500);
    }
}
